Rework Dockerfile
jsf9k/gatherer pull request #50
Opened 2019-11-29 17:50 UTC by jsf9k

# 

## 🗣 Description

Clean up the `Dockerfile` a la the changes recently made in cisagov/scanner#34 and cisagov/scanner#36.

This involves getting rid of the deprecated `MAINTAINER` tag and moving to a multistage build.

## 💭 Motivation and Context

These changes update the Docker image to use Debian Buster, remove the deprecated `MAINTAINER` tag, and leverage a multistage build to better organize the `Dockerfile` contents.

## 🧪 Testing

Verified that the new image and the previous one both generate the same list of hosts to be gathered.

## 🚥 Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (causes existing functionality to change)

## ✅ Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2019-11-29 18:00 UTC, felddy approved these changes
Nice!  Multi-stage FTW.   I'm glad you've done this, so I can crib.  
🦃 👍

2019-12-02 06:27 UTC, mcdonnnj requested changes
Nice rework, I'm digging the multi-stage 💪 Please see my comment about that variable though.

2019-12-02 06:27 UTC, mcdonnnj commented on Dockerfile
> +RUN apt-get remove --quiet --quiet $BUILD_DEPS
Was this supposed to be INSTALL_DEPS?

2019-12-02 13:10 UTC, jsf9k commented on Dockerfile
> +RUN apt-get remove --quiet --quiet $BUILD_DEPS
Good catch!  Fixed in 1271197.

2019-12-02 15:06 UTC, mcdonnnj approved these changes
Nice job 🤙

2019-12-02 16:16 UTC, dav3r approved these changes
LGTM, with one comment that will sound very familiar
🍪

2019-12-02 16:16 UTC, dav3r commented on Dockerfile
> +RUN pip install --no-cache-dir --upgrade pip setuptools
May want to add a comment somewhere in here about why we aren't using a pip cache (similar to what you did over [here](https://github.com/cisagov/saver/pull/46/commits/6781a3e8af53a3bbb8157827717144e8f0882d89)).

2019-12-02 19:02 UTC, jsf9k commented on Dockerfile
> +RUN pip install --no-cache-dir --upgrade pip setuptools
Remedied in commits 546f23f, cisagov/scanner@2b265d6, and cisagov/saver@eb7ae0d.

2019-12-02 19:07 UTC, dav3r approved these changes
👍 👍

2019-12-02 19:10 UTC, merged