⚠️ CONFLICT! Lineage pull request for: skeleton
jsf9k/gatherer pull request #93
Opened 2022-11-21 23:24 UTC by cisagovbot

# Lineage Pull Request: CONFLICT #

<img align="left" width="100" src="https://raw.githubusercontent.com/cisagov/action-lineage/develop/src/achtung.gif">

[Lineage] has created this pull request to incorporate new changes found in an
upstream repository:

Upstream repository: [`https://github.com/cisagov/skeleton-docker.git`](https://github.com/cisagov/skeleton-docker.git)
Remote branch: `HEAD`

Check the changes in this pull request to ensure they won't cause issues with
your project.

The `lineage/skeleton` branch has **one or more unresolved merge conflicts**
that you must resolve before merging this pull request!

## How to resolve the conflicts ##

1. Take ownership of this pull request by removing any other assignees.

1. Clone the repository locally, and reapply the merge:

    ```console
    git clone git@github.com:cisagov/gatherer.git gatherer
    cd gatherer
    git remote add skeleton https://github.com/cisagov/skeleton-docker.git
    git remote set-url --push skeleton no_push
    git switch develop
    git checkout -b lineage/skeleton --track origin/develop
    git pull skeleton HEAD
    git status
    ```

1. Review the changes displayed by the `status` command.  Fix any conflicts and
   possibly incorrect auto-merges.

1. After resolving each of the conflicts, `add` your changes to the
   branch, `commit`, and `push` your changes:

    ```console
    git add .github/dependabot.yml README.md bump_version.sh 
    git commit
    git push --force --set-upstream origin lineage/skeleton
    ```

    Note that you may *append* to the default merge commit message
    that git creates for you, but *please do not delete the existing
    content*.  It provides useful information about the merge that is
    being performed.

1. Wait for all the automated tests to pass.

1. Check the "Everything is cool" checkbox below:

    - [ ] ✌️ The conflicts in this pull request have been resolved.

1. Mark this draft pull request "Ready for review".

---

**Note:** *You are seeing this because one of this repository's maintainers has
configured [Lineage] to open pull requests.*

For more information:

🛠 [Lineage] configurations for this project are stored in `.github/lineage.yml`

📚 [Read more about Lineage][Lineage]

[//]: # (lineage:metadata:{&quot;slayed&quot;:true})
[Lineage]: https://github.com/cisagov/action-lineage/ "Lineage GitHub Action"

2022-11-22 17:17 UTC, jsf9k approved these changes

2022-11-28 20:12 UTC, dav3r approved these changes

2022-12-16 16:54 UTC, mcdonnnj requested changes
Please change https://github.com/cisagov/gatherer/blob/cb66bfdaca6c539b65f8c71d381f77c261c6c1a7/Dockerfile#L106 to `run`.

2022-12-16 16:54 UTC, mcdonnnj commented on Dockerfile
>  ARG VERSION
This argument is not used in this configuration.

2022-12-16 16:54 UTC, mcdonnnj commented on Dockerfile
>  RUN rm -rf /var/lib/apt/lists/*
```suggestion
RUN apt-get --quiet --quiet clean
    && rm --recursive --force /var/lib/apt/lists/*
```

2022-12-16 16:54 UTC, mcdonnnj commented on Dockerfile
>  RUN chown -R ${CISA_USER}:${CISA_GROUP} ${CISA_HOME}
```suggestion
RUN chown --recursive ${CISA_USER}:${CISA_GROUP} ${CISA_HOME}
```

2022-12-16 16:54 UTC, mcdonnnj commented on .github/labels.yml
> +- color: "ef476c"
```suggestion
- color: "3772a4"
  description: Pull requests that update Python code
  name: python
- color: "ef476c"
```

2022-12-16 17:08 UTC, jsf9k commented
> Please change
> 
> https://github.com/cisagov/gatherer/blob/cb66bfdaca6c539b65f8c71d381f77c261c6c1a7/Dockerfile#L106
> 
> to `run`.

Please see commit e974771.

2022-12-16 17:08 UTC, jsf9k commented on Dockerfile
>  ARG VERSION
Please see commit 3ed6100.

2022-12-16 22:59 UTC, mcdonnnj approved these changes

2022-12-19 14:57 UTC, merged